### PR TITLE
Adds the target

### PR DESCRIPTION
**Pull request by RamonGilabert**
Don't know if that should do it already, I think it should, checked the script, don't understand shit, but I think it will change `SwiftPackage` for the name of your pod. Is that right, @hyperoslo/malibu?

### CODE REVIEW

**Comment by vadymmarkov** [comment]
@RamonGilabert Yes, as I remember.

**Comment by vadymmarkov** [comment]
@RamonGilabert :star:

**Comment by RamonGilabert** [comment]
Yay!

**Comment by zenangst** [comment]
:+1:

**Pull request merged**
